-- 사용자 테스트 계정 생성 --

INSERT INTO PUBLIC.GROUP_TABLE (USER_ID, ROLE) VALUES (1, 'ROLE_USER');

INSERT INTO PUBLIC.USER_TABLE (USER_ID, CELL_PHONE, CREATE_DATE, EMAIL, LOCATION, NAME, NICKNAME, PASSWORD, SCORE, UPDATE_DATE, USERNAME) VALUES (1, '010-1234-5678', null, 'numble@test.com', '서울시 마포구', '테스트이름', '테스트닉네임', '$2a$10$04b3aEVuKlT5/rAI5WYCPesNGReYFxOTtvU9bFOIfEY7fRQUoYaqS', 0, null, 'dmstjd1024'); // 비밀번호 123456

INSERT INTO PUBLIC.USER_TABLE_ROLE (USER_BEAN_USER_ID, ROLE_USER_ID) VALUES (1, 1);
